// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpSGQUw6yVCOBx7bH6LfHMpTXsV3v4GGc',
    appId: '1:1085858249070:web:6898c3adc27414f427697f',
    messagingSenderId: '1085858249070',
    projectId: 'waisaka-mobile',
    authDomain: 'waisaka-mobile.firebaseapp.com',
    storageBucket: 'waisaka-mobile.firebasestorage.app',
    measurementId: 'G-KDB3GXC0DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBamXOP_WcLTzVqHibmtXVt9_PrXatgjI8',
    appId: '1:1085858249070:android:3ee8ab29a064545527697f',
    messagingSenderId: '1085858249070',
    projectId: 'waisaka-mobile',
    storageBucket: 'waisaka-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-6XORwWqBBUA8THR8tB1DxB2WcxodTw',
    appId: '1:1085858249070:ios:caaedfc8461b00e727697f',
    messagingSenderId: '1085858249070',
    projectId: 'waisaka-mobile',
    storageBucket: 'waisaka-mobile.firebasestorage.app',
    iosBundleId: 'com.example.waisaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-6XORwWqBBUA8THR8tB1DxB2WcxodTw',
    appId: '1:1085858249070:ios:caaedfc8461b00e727697f',
    messagingSenderId: '1085858249070',
    projectId: 'waisaka-mobile',
    storageBucket: 'waisaka-mobile.firebasestorage.app',
    iosBundleId: 'com.example.waisaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpSGQUw6yVCOBx7bH6LfHMpTXsV3v4GGc',
    appId: '1:1085858249070:web:236153a032fdd50027697f',
    messagingSenderId: '1085858249070',
    projectId: 'waisaka-mobile',
    authDomain: 'waisaka-mobile.firebaseapp.com',
    storageBucket: 'waisaka-mobile.firebasestorage.app',
    measurementId: 'G-GS21RF7MTH',
  );
}
